title: Matthew Norman
logo: /assets/img/headshot.png
description: Educator & Analyst Hybrid | Skilled in SQL, Tableau, R | Turning Complex Data into Clear Decisions
show_downloads: false
theme: jekyll-theme-minimal
